[package]
name = "egyptian-war"
version = "0.1.0"
authors = ["Daniel Kavanagh <dan.kava13@gmail.com>"]

[dependencies]
#cards = { git = "https://github.com/danno131313/rust-cards" }
cards = { path = "../cards" }
ncurses = "5.86.0"
